id: smart.who.int.pcmt-vaxprequal
canonical: http://smart.who.int/pcmt-vaxprequal
name: PCMTVAXPreQual
title: SMART Product Dataset for Prequalified Vaccines
description: Data exchange specifications for Product Catalog supporting the SMART
  Guidelines
status: draft
version: 0.2.0
fhirVersion: 4.0.1
copyrightYear: 2023+
releaseLabel: release
publisher:
  name: WHO
  url: http://who.int
meta:
  profile:
  - http://smart.who.int/smart-base/ImplementationGuide-SGImplementationGuide
pages:
  index.md:
    title: Home
    changes.md:
      title: Changes
    dependencies.md:
      title: Dependencies
    references.md:
      title: References
    adapting.md:
      title: Adapting Guidelines for Country use
    license.md:
      title: License
  business-requirements.md:
    title: Business Requirements
    concepts.md:
      title: Concepts
    personas.md:
      title: Generic Personas
    scenarios.md:
      title: User Scenarios
    business-processes.md:
      title: Business Processes
    dictionary.md:
      title: Data Dictionary
    decision-logic.md:
      title: Decision-support logic
    indicators.md:
      title: Indicator and Performance Metrics
    functional-requirements.md:
      title: Functional Requirements
    non-functional-requirements.md:
      title: Non-functional Requirements
  data-models-and-exchange.md:
    title: Data Models and Exchange
    system-actors.md:
      title: System Actors
    sequence-diagrams.md:
      title: Sequence Diagrams
    transactions.md:
      title: Transactions
    indicators-measures.md:
      title: Indicators and Measures
    codings.md:
      title: Codings
  deployment.md:
    title: Deployment
    security-privacy.md:
      title: Security and Privacy Considerations
    testing.md:
      title: Testing
    test-data.md:
      title: Test Data
    reference-implementations.md:
      title: Reference Implementations
    trust_domain.md:
      title: Trust Domains
    downloads.md:
      title: Downloads
  indices.md:
    title: Indices
    artifacts.html:
      title: Artifact Index
    maps.md:
      title: Mappings
  dak-api.md:
    title: DAK API Documentation Hub
menu:
  Home:
    Summary: index.html
    Changes: changes.html
    Dependencies: dependencies.html
    References: references.html
    Adapting Guidelines for Country use: adapting.html
  Business Requirements:
    Concepts: concepts.html
    Generic Personas: personas.html
    User Scenarios: scenarios.html
    Business Processes: business-processes.html
    Data Dictionary: dictionary.html
    Decision-support Logic: decision-logic.html
    Indicator and Performance Metrics: indicators.html
    Functional Requirements: functional-requirements.html
    Non-functional Requirements: non-functional-requirements.html
  Data Models and Exchange:
    System Actors: system-actors.html
    Sequence Diagrams: sequence-diagrams.html
    Transactions: transactions.html
    Indicators and Measures: indicators-measures.html
    Codings: codings.html
  Deployment:
    Security and Privacy Considerations: security-privacy.html
    Testing: testing.html
    Test Data: test-data.html
    Reference Implementations: reference-implementations.html
    Trust Domains: trust_domain.html
    Downloads: downloads.html
  Indices:
    Artifact Index: artifacts.html
    Mappings: maps.html
    DAK API: dak-api.html
dependencies:
  smart.who.int.base: 0.1.0
  smart.who.int.pcmt: 0.1.0
  ihe.iti.mcsd:
    id: IHE_ITI_mCSD
    uri: https://profiles.ihe.net/ITI/mCSD/ImplementationGuide/ihe.iti.mcsd
    version: 4.0.0
